server {
    listen 80;
    server_name localhost;

    root /var/www/laravel/public;
    index index.php;

    location / {
        fastcgi_pass auth-service:9000;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME /var/www/laravel/public/index.php;
        fastcgi_param PATH_INFO $uri;
        fastcgi_param REQUEST_URI $request_uri;
    }

    client_max_body_size 64M;
}