server {
    listen 80;
    server_name localhost;

    root /var/www/laravel/public;
    index index.php;

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass user-php:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/laravel/public$fastcgi_script_name;
    }

    client_max_body_size 64M;
}
